In [1]:
import numpy as np


In [2]:
import numpy as np
arr =  np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array(([[1,2,3,4], 
                 [4,5,6,7]]))
print("Shape:", arr.shape) #rows, cloumns
print("Size:", arr.size)
print("Data type:", arr.dtype)



Shape: (2, 4)
Size: 8
Data type: int64


In [9]:
zeros_arr = np.zeros((3,4)) #3*4
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones_arr = np.ones((2,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
range_arr = np.arange(10)
print(range_arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
range_arr = np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [23]:
dot_product = np.dot(a,b)
print("Dot product:", dot_product)

Dot product: 32


In [30]:
arr = np.arange(1,10)
print(arr)
reshaped_arr = arr.reshape(3,3)
print(reshaped_arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr = np.array([1,2,3,4,5,6])
print("First element:", arr[0])
print("Slice from index 1 to 3:", arr[1:4])

First element: 1
Slice from index 1 to 3: [2 3 4]


In [33]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print("Element at row 1, column 2:", arr_2d)
print("First row:", arr_2d[0, :])
print("Second column:", arr_2d[:, 1])


Element at row 1, column 2: [[1 2 3]
 [4 5 6]]
First row: [1 2 3]
Second column: [2 5]


In [35]:
arr = np.array([1,2,3,4,100,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

Sum: 115
Mean: 19.166666666666668
Min: 1
Max: 100


In [36]:
random_arr = np.random.random((3,3))
print(random_arr)

[[0.78218982 0.99852121 0.80142536]
 [0.86265506 0.31886018 0.39756823]
 [0.77176512 0.68416996 0.06452099]]


In [44]:
random_int = np.random.randint(1,10, size =(2,3))
print(random_int)

[[8 2 7]
 [2 4 4]]


In [60]:
random_numbers = np.random.randint(1,100, size= (4,4))
print(random_numbers)
print("Random mean in each row:", np.mean(random_numbers[0,:]))
print("Random mean in each column:", np.mean(random_numbers[1,:]))
print("reshape random:", random_numbers.reshape(2,8))
print("Sum of each column:", np.sum(random_numbers[1,:]))

[[78 14 31 84]
 [29 89 68 20]
 [ 4 29 61 98]
 [78  7 84 11]]
Random mean in each row: 51.75
Random mean in each column: 51.5
reshape random: [[78 14 31 84 29 89 68 20]
 [ 4 29 61 98 78  7 84 11]]
Sum of each column: 206


In [45]:
arr = np.array([1,2,3])
np.save("My array.npy", arr)

In [48]:
loaded_arr = np.load('My array.npy')
print(loaded_arr)

[1 2 3]
