In [3]:
import numpy as np
def fahr_to_temp(f):
    return (np.array(f)-32)*5/9
f=[32, 68, 100, 212, 77]
result = fahr_to_temp(f)
print("Temperature in Celcious:", result)
print("result 1:", result[0])
print("result 2:", result[1])
print("result 3:", result[2])
print("result 4:", result[3])
print("result 5:", result[4])

Temperature in Celcious: [  0.          20.          37.77777778 100.          25.        ]
result 1: 0.0
result 2: 20.0
result 3: 37.77777777777778
result 4: 100.0
result 5: 25.0


In [4]:
x = np.array([2,3,4,5])
p = np.array([1,2,3,4])
np.power(x,p)

array([  2,   9,  64, 625])

In [6]:
x= np.array([
[4,5,6],
[3,-1,1],
[2,1,-2]
])

y = np.array([7,4,5])
d=np.linalg.solve(x,y)
print("x:", d[0])
print("y:", d[1])
print("z:", d[2])

x: 1.7027027027027029
y: 0.6216216216216216
z: -0.4864864864864865


In [7]:
a = np.array([
[10, -2, 3],
[-2, 8, -1],
[3, -1, 6]
])

b = np.array([12, -5, 15])

result = np.linalg.solve(a,b)
print("l1:", result[0])
print("l2:", result[1])
print("l3:", result[2])

l1: 0.48963730569948194
l2: -0.2253886010362694
l3: 2.2176165803108807


In [15]:
import numpy as np
from PIL import Image
with Image.open('birds.jpg') as img:

    image_arrey = np.array(img)
print(image_arrey.shape)

(148, 217, 3)


In [16]:
import numpy as np
from PIL import Image


with Image.open('birds.jpg') as img:
 
    image_array = np.array(img)
    print(image_array)

def flip_image(img):
    return
flipped_horizontal = image_array[:, ::-1, :]
print(flipped_horizontal)

[[[199 207 194]
  [194 202 189]
  [187 195 184]
  ...
  [141 148 130]
  [144 151 133]
  [142 151 132]]

 [[199 207 194]
  [194 202 189]
  [186 194 183]
  ...
  [136 143 125]
  [139 146 128]
  [141 150 131]]

 [[199 207 192]
  [193 201 186]
  [185 193 180]
  ...
  [132 140 119]
  [133 141 120]
  [140 149 128]]

 ...

 [[242 245 254]
  [241 244 253]
  [239 244 250]
  ...
  [169 147 110]
  [182 160 123]
  [190 167 133]]

 [[242 245 254]
  [241 244 253]
  [239 244 250]
  ...
  [169 147 110]
  [170 148 111]
  [181 158 124]]

 [[242 245 254]
  [241 244 253]
  [239 244 250]
  ...
  [174 152 115]
  [168 146 109]
  [154 131  97]]]
[[[142 151 132]
  [144 151 133]
  [141 148 130]
  ...
  [187 195 184]
  [194 202 189]
  [199 207 194]]

 [[141 150 131]
  [139 146 128]
  [136 143 125]
  ...
  [186 194 183]
  [194 202 189]
  [199 207 194]]

 [[140 149 128]
  [133 141 120]
  [132 140 119]
  ...
  [185 193 180]
  [193 201 186]
  [199 207 192]]

 ...

 [[190 167 133]
  [182 160 123]
  [169 147 110]
  ..

In [17]:
import numpy as np

flipped_vertical = image_array[::-1, :, :]  


Image.fromarray(flipped_vertical).show()